### ISSUE TITLE
How do I use python34u with uwsgi?

### ISSUE THREAD

**Issue by x-yuri** [iuscommunity-pkg/python34u#3]
When I try to install python34u and uwsgi-plugin-python3, I get [a conflict](https://gist.github.com/x-yuri/4ed5962f391e9a5d63cbf4bd87cce714). Any workaround?

**Comment by carlwgeorge** [comment]
Both IUS and EPEL have Python 3.4 stacks, named python34u and python34, respectively.  The files from these packages conflict with each other because they use the same path.  

file /usr/bin/python3.4 from install of **_python34u_**-3.4.5-1.ius.centos7.x86_64 conflicts with file from package **_python34_**-3.4.3-7.el7.x86_64

Based on your gist output, you currently have python34u (IUS) installed, but are trying to install uwsgi-plugin-python3 (EPEL), which explicitly requires python34 (EPEL).  If  you want to use uwsgi-plugin-python3 (EPEL), you need to uninstall all your python34u (IUS) packages first.  Alternatively, we [just added uwsgi-plugin-python35u](https://github.com/iuscommunity/wishlist/issues/90) to IUS, so if Python 3.5 is acceptable, you can switch to that instead.  If you want to stick with python34u (IUS) but want to use it with uwsgi, you can [open a wishlist request](https://github.com/iuscommunity/wishlist/blob/master/CONTRIBUTING.md) for us to create uwsgi-plugin-python34u.

**Comment by x-yuri** [comment]
First, I wanted to explain why `python34` didn't do. EPEL's Python 3.4 stack lacks `pip`. That's why I decided to switch to IUS' one.

Second, I can see [uwsgi-plugin-python34u](https://github.com/iuscommunity-pkg/uwsgi-plugin-python34u) as well.

**Comment by carlwgeorge** [comment]
Yeah, I've heard others discuss the troubles with EPEL's python34.  We are certainly happy you decided to try our packages instead.

We created a spec file for uwsgi-plugin-python34u a while back (based on [this request](https://github.com/iuscommunity/wishlist/issues/11)), but it was never finalized and added to the stable repo.  For that to happen, we need to update it to match the current EPEL version of uwsgi (2.0.13.1), and have a user (perhaps yourself) test it and confirm that it works as expected.  Otherwise I'd just recommend using the existing uwsgi-plugin-python35u (with python35u of course).

**Comment by x-yuri** [comment]
Well, I can at least test if my very basic app (for now) runs successfully with python34u. If that will suffice, what should I do? AFAIR, I didn't see it in any of your repos (e.g., ius-testing). Or what exactly do you mean by testing? It's gonna be my very first python app, so I'm not sure I can give pretty much authoritative feedback. But if anything comes up, I can certainly report to you.

**Comment by b-harper** [comment]
Hey @x-yuri,

Great question.  With a limited resources, we want to avoid new package requests that are like 'I don't have use for foo, but I think it would be cool if IUS packaged foo'.   To combat this, we ask the requester (or someone else) to test the package before we put it into  the stable repositories.  We are looking to see if the package works for your needs and we aren't looking to you to test every feature and option.

Since the [original request](https://github.com/iuscommunity/wishlist/issues/11) stalled out, we moved the package from the testing repository to the development repository (ius-dev).  Give it a try and update the [original request](https://github.com/iuscommunity/wishlist/issues/11).

-Ben
